language: php
php:
  - 7.1
  - 7.2
  - 7.3
cache:
  directories: $HOME/.composer/cache
before_install: composer self-update
script: vendor/bin/phpunit
before_script: composer install --no-interaction --dev
